### ISSUE TITLE
Printf

### ISSUE THREAD

**Issue by peekpt** [idea--list/Adafruit-GFX-Library-Arduino-Mbed#1]
Hello, thank you for doing this. I also use this lib in both Arduino and Mbed.
I'm trying to use your lib on Mbed but all my code is already using printf, is it possible to add printf functionality on Mbed only?

**Comment by idea--list** [comment]
@peekpt 
mbed-os supports prinf() like you can find [here](https://os.mbed.com/docs/mbed-os/v5.15/tutorials/debugging-using-printf-statements.html) or [here](http://www.cplusplus.com/reference/cstdio/printf/)

Note however that while porting this library to Mbed, i also copy&pasted some original arduino files like print.h, print.cpp, etc. Am not sure if those might have affected how printf() in Mbed works.
In that case however i can not help as currently i do not have enough time to find the cause and rewrite all the needed code.

**Comment by peekpt** [comment]
@idea--list Yes I noticed that. I'm using another port of Adafruit_GFX ( with printf ) on Mbed but your looks to be recent with font support. That's why I was interested.  I thought it could be an easier implementation. Thanks anyway.
